language: java
cache:
  timeout: 1000
  directories:
  - $HOME/.m2
before_install:
    - git clone https://github.com/jeddict/netbeans-modeler.git ~/builds/netbeans-modeler
    - pushd ~/builds/netbeans-modeler/modeler-lib/repository/org/analytics/analytics/1.0
    - mvn install:install-file -Dfile=analytics-1.0.jar -DgroupId=org.analytics -DartifactId=analytics -Dversion=1.0 -Dpackaging=jar
    - popd
    - pushd ~/builds/netbeans-modeler
    - mvn clean install
    - popd
    - pushd jcode-core/repository/org/graalvm/graalvm/graaljs/1.0.0-rc6
    - mvn install:install-file -Dfile=graaljs-1.0.0-rc6.jar -DgroupId=org.graalvm -DartifactId=graaljs -Dversion=1.0.0-rc6 -Dpackaging=jar
    - popd
    - pushd jcode-core/repository/org/graalvm/graalvm/graaljs-scriptengine/1.0.0-rc6
    - mvn install:install-file -Dfile=graaljs-scriptengine-1.0.0-rc6.jar -DgroupId=org.graalvm -DartifactId=graaljs-scriptengine -Dversion=1.0.0-rc6 -Dpackaging=jar
    - popd
    - pushd jcode-core/repository/org/graalvm/graalvm/tregex/1.0.0-rc6
    - mvn install:install-file -Dfile=tregex-1.0.0-rc6.jar -DgroupId=org.graalvm -DartifactId=tregex -Dversion=1.0.0-rc6 -Dpackaging=jar
    - popd